---
title: "Gun Violence Data"
author: "Hayley Hadges, Ethan Deutsch, Em Hayward"
date: "4/23/2020"
output: html_document
---


```{r,echo=FALSE}
library(tidyverse)
library(janitor)
library(tidyverse) #for plotting and summarizing
library(GGally) #for nice scatterplot matrix 
library(ggridges) #for joy/ridge plots
library(corrplot) #for basic correlation matrix plot
library(naniar) #for exploring missing values
library(pdp) #for partial dependence plots, MARS models

#making things look nice
library(lubridate) #for nice dates
library(knitr) #for nice tables
library(scales) #for nice labels on graphs
library(gridExtra) #for arranging plots
library(broom) #for nice model output

#data
library(ISLR) #for data
library(moderndive) #for data

#modeling
library(rsample) #for splitting data
library(recipes) #for keeping track of any transformations we do
library(caret) #for modeling
library(leaps) #for variable selection
library(glmnet) #for LASSO
library(earth) #for MARS models
library(vip) #NEW for importance plots

library(usmap)
library(ggplot2)
library(tidyverse)

library(rpart)
library(rpart.plot)
library(expss)
library(data.table)
library(formattable)
theme_set(theme_minimal())
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
gvd <- read_csv("GunViolenceData.csv")
```
```{r, echo = FALSE}
levels(gvd$state)
```
```{r}
colnames(gvd)
```



```{r, echo = FALSE}
#create a new date column on clean data that is of the Date datatype
datefixed <- gvd
datefixed['new_date']<-as.Date(as.character(gvd$date), format='%m/%d/%Y')
class(datefixed$new_date)
```


Should we delete these since we took out the week and day variables?
```{r}
# gun violence grouped by WEEK arranged in chronological order
# note to reverse order just edit arrange(desc(week))

totalsByWeek <- datefixed %>%
  group_by(week) %>%
  summarize(total=n()) %>%
  arrange(week)
```

```{r}
totalsByDay <- datefixed %>%
  group_by(day) %>%
  summarize(total=n()) %>%
  arrange(day)
```




```{r, echo = FALSE}
# gun violence grouped by state order descending

dataByState <- datefixed %>%
  group_by(state) %>%
  summarize(n=n()) %>%
  arrange(desc(n))
```

```{r, echo = FALSE}
cleandata <- 
  datefixed%>%
  mutate(female_present = str_detect(participant_gender, "Female")) %>% 
  mutate(teen_present = str_detect(participant_age_group, "Teen 12-17")) %>% 
  mutate(child_present = str_detect(participant_age_group, "Child 0-11")) %>% 
  mutate_if(is.character, replace_na, replace = "missing") %>%
  mutate_if(is.logical, replace_na, replace ="missing") %>% 
  select(-c(incident_id, incident_url_fields_missing, address, incident_url, source_url, incident_characteristics, location_description, notes, participant_name, participant_relationship, sources))

```

```{r, echo = FALSE}
set.seed(253) 
gv_split <- initial_split(cleandata, 
                             prop = .5)
gv_train <- training(gv_split)
gv_test <- testing(gv_split)
```



```{r}
colnames(gv_train)

# gives the data type of each column, helpful for debugging weird errors with types. Many of the types are factors
# but many functions cant operate on factors.
map(gv_train, class)
```




```{r}
library(tidyverse)
#cleandata$participant_gender <- str_replace(cleandata$participant_gender, "||", ",")
#cleandata$participant_gender <- str_replace(cleandata$participant_gender, "::", "")
#cleandata$participant_gender <- str_replace(cleandata$participant_gender, "[0123]", "")

```



```{r, echo = FALSE}
gv_train %>%
  group_by(city_or_county) %>%
  summarize(n=n()) %>%
  arrange(desc(n))
```


Should we make plots with categorical variables?
```{r}
plot1 <- gv_train %>%
  ggplot(aes(x=new_date, y=n_killed)) +
  geom_point()
plot1
```

```{r}
plot2 <- gv_train %>%
  ggplot(aes(x=new_date, y=n_injured)) +
  geom_point()
plot2
```

```{r}
plot3 <- gv_train %>%
  ggplot(aes(x = female_present, y = n_killed)) +
  geom_boxplot()
plot3
```

```{r}
plot4 <- gv_train %>%
  ggplot(aes(x = teen_present, y = n_killed)) +
  geom_boxplot()
plot4
```



```{r}
plot_usmap(data = dataByState, values = "n", color = "black") +
  scale_fill_continuous(low = "white", high = "orchid3", name = "Total Violence (2018)", label = scales::comma) + theme(legend.position = "right")
```
```{r, echo = FALSE}
deaths <- gvd %>% 
  filter(n_killed > 0)

injured <- gvd %>% 
  filter(n_killed < 1) %>%
  filter(n_injured > 0)

nobodyHurt <- gvd %>% 
  filter(n_killed < 1) %>% 
  filter(n_injured < 1)
  
nrow(deaths)
nrow(injured)
nrow(nobodyHurt)
```
```{r, echo = FALSE}
dataByState <- deaths %>%
  group_by(state) %>%
  summarize(n=n()) %>%
  arrange(desc(n))


plot_usmap(data = dataByState, values = "n", color = "black") +
  scale_fill_continuous(low = "white", high = "orchid3", name = "Number Of Deaths (2018)", label = scales::comma) + theme(legend.position = "right")

dataByState <- injured %>%
  group_by(state) %>%
  summarize(n=n()) %>%
  arrange(desc(n))


plot_usmap(data = dataByState, values = "n", color = "black") +
  scale_fill_continuous(low = "white", high = "orchid3", name = "Number Injured (2018)", label = scales::comma) + theme(legend.position = "right")

dataByState <- nobodyHurt %>%
  group_by(state) %>%
  summarize(n=n()) %>%
  arrange(desc(n))


plot_usmap(data = dataByState, values = "n", color = "black") +
  scale_fill_continuous(low = "white", high = "orchid3", name = "Nobody Hurt (2018)", label = scales::comma) + theme(legend.position = "right")
```
```{r, echo = FALSE}
dataByCounty <- datefixed %>%
  group_by(city_or_county) %>%
  summarize(n=n()) %>%
  arrange(desc(n))
```




```{r, echo = FALSE}
#I used backward selection to find the numeric variables give the smallest cross-validated RMSE in the model.
gv_train_num <- gv_train %>% 
  select_if(is.numeric)


set.seed(253)
splits <- trainControl(method = "cv", number = 5)

gv_cv_vars <- train(
  n_killed ~ .,
  data = gv_train_num,
  method = "leapBackward", #NEW method!
  tuneGrid = data.frame(nvmax = 1:8),
  trControl = splits,
  na.action = na.omit
)
```

```{r, echo = FALSE}
#RMSE of 0.5156813	
summary(gv_cv_vars)
gv_cv_vars$results

#Best numeric variables include:
#n_injured
#latitude
#n_guns_involved
#longitude
```

```{r, echo = FALSE}
#This model uses the four numeric variables from the previous model
set.seed(253) 
gv_ols <- train(
  n_killed ~ n_injured + latitude + n_guns_involved + longitude,
  data = gv_train, 
  method = "lm",
  trControl = splits, 
  na.action = na.omit
)

gv_ols$results
#RMSE of 0.5039284	
```

```{r, echo = FALSE}
#This model uses the variables that equate with the smallest RMSE in an OLS model
set.seed(253) 
gv_ols2 <- train( 
  n_killed ~ n_injured + latitude + n_guns_involved + longitude + female_present + teen_present +  state + new_date,
  data = gv_train, 
  method = "lm",
  trControl = splits, 
  na.action = na.omit
)

gv_ols2$results
#RMSE of 0.4736671	
```

```{r}
lambda_grid <- 10^seq(-4, -1 , length = 50)

set.seed(253)
gv_lasso <- train(
  n_killed ~ n_injured + latitude + n_guns_involved + longitude + female_present + teen_present +  state + new_date,
  data = gv_train, 
  method = "glmnet",
  tuneGrid = data.frame(alpha = 1, lambda = lambda_grid),
  trControl = splits,
  na.action = na.omit,
  metric = "RMSE", 
  maximize = FALSE
)

gv_lasso$bestTune$lambda
gv_lasso$results

#RMSE of 0.4732095		
```

```{r, echo = FALSE}
#Says there are missing values in n_killed
set.seed(253)

gv_mars <- train(
  n_killed ~ n_injured + latitude + n_guns_involved + longitude + female_present + teen_present +  state + new_date,
  data = gv_train, 
  method = "earth",
  trControl = trainControl(method = "cv",
                           number = 5),
  tuneGrid = data.frame(degree = 1, nprune = 4:12),
  na.action = na.omit
)
```
```{r}
gv_mars$bestTune
gv_mars$results
#RMSE of 0.4640177
```

```{r, echo = FALSE}
set.seed(253)

gv_class_tree <- train(
  n_killed ~   n_injured + latitude + n_guns_involved + longitude + female_present + teen_present +  state + new_date,
  data = gv_train,
  method = "rpart",
  tuneGrid = data.frame(cp = .5),
  trControl = trainControl(method = "cv", number = 5),
  metric = "RMSE",
  na.action = na.omit
)
```

```{r, echo = FALSE}
gv_class_tree$results
#RMSE of 0.519345	
```



```{r, echo = FALSE}
set.seed(253)
gv_tree_oob <- train(
  n_killed ~ n_injured + latitude + n_guns_involved + longitude + female_present + teen_present +  state + new_date,
  data = gv_train, 
  method = "rf",
  trControl = trainControl(method = "oob"),
  tuneGrid = data.frame(mtry = 10),
  ntree = 50, 
  importance = TRUE, 
  nodesize = 5, 
  na.action = na.omit
)

```

```{r, echo = FALSE}
gv_tree_oob$results
plot(gv_tree_oob$finalModel)
#RMSE of 0.4452655	
```

```{r, echo = FALSE}
RMSE <- matrix(c(0.5156813, 0.4736671, 0.4732095, 0.4640177, 0.519345, 0.445265	))
rownames(RMSE) <- c("Step Backwards","OLS", "Lasso", "Mars", "Tree", "Random Forest")
colnames(RMSE) <- ("RMSE")

RMSE
```

```{r}
vip(gv_tree_oob$finalModel, num_features = 16, bar = FALSE)
```

Partial Dependency plots here:
n_injured + latitude + n_guns_involved + longitude + female_present + teen_present +  state + new_date
```{r}

partial(
  gv_tree_oob, 
  pred.var = "n_injured",
  grid.resolution = 20
  ) %>% 
  autoplot()

partial(
  gv_tree_oob, 
  pred.var = "n_guns_involved",
  grid.resolution = 20
  ) %>% 
  autoplot()

partial(
  gv_tree_oob, 
  pred.var = "latitude",
  grid.resolution = 20
  ) %>% 
  autoplot()

partial(
  gv_tree_oob, 
  pred.var = "new_date",
  grid.resolution = 20
  ) %>% 
  autoplot()
```
